repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/ambv/black
  rev: 22.8.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear==22.8.23]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
  - id: mypy
    language_version: python3
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
