repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.11.0
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.6
    args: [--py36]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==19.3.0']
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.650
  hooks:
  - id: mypy
- repo: https://github.com/asottile/blacken-docs
  rev: v0.3.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==18.9b0]
    args: [--py36]
