trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [lint, py37, py38, py39, py310, py311]
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    python: "3.10"
    distributions: "sdist bdist_wheel"
    dependsOn:
      - tox_linux
